linuxdeepin/deepin-screensaver

- src/main.cpp
See: https://github.com/linuxdeepin/qt5integration/blob/0.3.11/platformthemeplugin/qdeepintheme.cpp#L598
修复高分屏缩放失效
> fix: no scale on HI-DPI screens

- xscreensaver/xscreensaver.pro
https://github.com/linuxdeepin/internal-discussion/issues/1665
> remove the "pacman" xscreensaver data

- README.md
> chore: adapt REUSE license

- customscreensaver/deepin-custom-screensaver/deepin-custom-screensaver.pro
- customscreensaver/deepin-custom-screensaver/src/main.cpp
- customscreensaver/deepin-custom-screensaver/src/slideshowscreensaver.cpp
- customscreensaver/deepin-custom-screensaver/src/slideshowscreensaver.h
- customscreensaver/deepin-custom-screensaver/translations/deepin-custom-screensaver.ts
- customscreensaver/deepin-custom-screensaver/translations/deepin-custom-screensaver_zh_CN.ts
When there is no picture in custom-screensaver's Settings directory, the screensaver should display black
Log: fix the issue of custom-screensaver screen display
Bug: https://pms.uniontech.com/bug-view-167341.html
> fix: the issue of custom-screensaver screen display

- customscreensaver/deepin-custom-screensaver/src/slideshowscreensaver.cpp
- customscreensaver/deepin-custom-screensaver/src/slideshowscreensaver.h
- customscreensaver/deepin-custom-screensaver/translations/deepin-custom-screensaver.ts
- customscreensaver/deepin-custom-screensaver/translations/deepin-custom-screensaver_zh_CN.ts
1. Increase weight calculation
2. Continuous same image processing
Log: fix In random mode, some images cannot be displayed for a long time
Bug: https://pms.uniontech.com/bug-view-168331.html
> fix: In random mode, some images cannot be displayed for a long time

- customscreensaver/deepin-custom-screensaver/src/slideshowscreensaver.cpp
1.Fixed the issue where playback would not loop when there were only two images
2.Fixed the issue where uppercase suffixes were not supported
Log: fix bugs
Bug: https://pms.uniontech.com/bug-view-171197.html
https://pms.uniontech.com/bug-view-172003.html
> fix: fix two bug of display

- customscreensaver/deepin-custom-screensaver/translations/deepin-custom-screensaver_zh_CN.ts
ad title
Log: fix no translations
Bug: https://pms.uniontech.com/bug-view-168331.html
> fix: fix no translations

- common.pri
- src/dbusscreensaver.cpp
- xscreensaver/xscreensaver.pro
Migrate the snipe branch to github.
Log: Added version adaptation.
Bug: https://pms.uniontech.com/task-view-224615.html
> feat: Migrate the snipe branch to github

- customscreensaver/deepin-custom-screensaver/data/deepin-custom-screensaver.conf
- customscreensaver/deepin-custom-screensaver/data/deepin-custom-screensaver.json
- customscreensaver/deepin-custom-screensaver/src/main.cpp
- customscreensaver/deepin-custom-screensaver/src/slideshowconfig.cpp
- customscreensaver/deepin-custom-screensaver/src/slideshowconfig.h
- customscreensaver/deepin-custom-screensaver/src/slideshowscreensaver.cpp
- customscreensaver/deepin-custom-screensaver/translations/deepin-custom-screensaver.ts
- customscreensaver/deepin-custom-screensaver/translations/deepin-custom-screensaver_zh_CN.ts
- src/customconfig.cpp
- src/screensaversettingdialog.cpp
- src/screensaversettingdialog.h
- src/selectpathwidget.cpp
- src/src.pro
- src/timeintervalwidget.cpp
- src/timeintervalwidget.h
- src/translations/deepin-screensaver.ts
- src/translations/deepin-screensaver_zh_CN.ts
as title
Log: updated the custom screensaver settings
Task: https://pms.uniontech.com/task-view-193285.html
> feat: Updated the custom screensaver settings

- src/timeintervalwidget.h
- xscreensaver/xscreensaver.pro
1.fix no xscreensaver
2.fix that there is no translation in parts
Log: fix some bugs
Task: https://pms.uniontech.com/task-view-193285.html
> feat: fix some bugs

- src/dbusscreensaver.cpp
using new power service org.deepin.dde.Power1 to set screensaver delay time.
Log:
Bug: https://pms.uniontech.com/bug-view-157751.html
> fix: adapt power service

- common.pri
- debian/control
- xscreensaver/xscreensaver.pro
using dtk_qmake to get os version.
Log: 
Bug: https://pms.uniontech.com/bug-view-181801.html
> fix: fail to get build os version.

- debian/changelog
update the new baseline version
Log:
Task: no link
> feat: update the new baseline version

- .obs/workflows.yml
- .reuse/dep5
obs build use beige develop repo
> chore(CI): change obs workflow

- customscreensaver/customscreensaver.pro
- customscreensaver/deepin-video-screensaver/commandlinemanager.cpp
- customscreensaver/deepin-video-screensaver/commandlinemanager.h
- customscreensaver/deepin-video-screensaver/data/video/.readme
- customscreensaver/deepin-video-screensaver/deepin-video-screensaver.pro
- customscreensaver/deepin-video-screensaver/main.cpp
- customscreensaver/deepin-video-screensaver/videoscreensaver.cpp
- customscreensaver/deepin-video-screensaver/videoscreensaver.h
- customscreensaver/deepin-video-screensaver/xproxywindow.cpp
- customscreensaver/deepin-video-screensaver/xproxywindow.h
- debian/control
- debian/deepin-screensaver-xscreensaver-data.install
- src/dbusscreensaver.cpp
- src/screensaverview.cpp
add  video screensaver.
Log:
Task: https://pms.uniontech.com/task-view-260281.html
Task: https://pms.uniontech.com/task-view-246639.html
Influence: 屏保
> feat: the frame of video screensaver

- src/dbusscreensaver.cpp
The screensaver exited by calling stop method of it or receiving  mouse move event t sent by xwayland and the idle state of xorg or wayland sever do not switch to off. So the screensaver will never startup again until  any inputs happens.
Log: 
Bug: https://pms.uniontech.com/bug-view-200789.html
Influence: 屏保
> fix: the idle state dont switch to off when screensaver exited without input event.

- .reuse/dep5
- .tx/config
- customscreensaver/deepin-custom-screensaver/translations/deepin-custom-screensaver_az.ts
- customscreensaver/deepin-custom-screensaver/translations/deepin-custom-screensaver_bo.ts
- customscreensaver/deepin-custom-screensaver/translations/deepin-custom-screensaver_ca.ts
- customscreensaver/deepin-custom-screensaver/translations/deepin-custom-screensaver_fi.ts
- customscreensaver/deepin-custom-screensaver/translations/deepin-custom-screensaver_pl.ts
- customscreensaver/deepin-custom-screensaver/translations/deepin-custom-screensaver_ru.ts
- customscreensaver/deepin-custom-screensaver/translations/deepin-custom-screensaver_uk.ts
- src/translations/deepin-screensaver_az.ts
- src/translations/deepin-screensaver_bo.ts
- src/translations/deepin-screensaver_ca.ts
- src/translations/deepin-screensaver_fi.ts
- src/translations/deepin-screensaver_pl.ts
- src/translations/deepin-screensaver_ru.ts
- src/translations/deepin-screensaver_sq.ts
- src/translations/deepin-screensaver_uk.ts
Log: add translations of Tibetan
> chore: add translations

- .reuse/dep5
- .tx/deepin.conf
- debian/changelog
> chore: update version to 5.0.18

- customscreensaver/deepin-custom-screensaver/data/deepin-custom-screensaver.desktop
- customscreensaver/deepin-custom-screensaver/data/org.deepin.customscreensaver.json
- customscreensaver/deepin-custom-screensaver/deepin-custom-screensaver.pro
- customscreensaver/deepin-custom-screensaver/src/commandlinemanager.cpp
- customscreensaver/deepin-custom-screensaver/src/main.cpp
- customscreensaver/deepin-custom-screensaver/src/slideshowconfig.cpp
- customscreensaver/deepin-custom-screensaver/src/slideshowconfig.h
- customscreensaver/deepin-custom-screensaver/src/slideshowconfigdialog.cpp
- customscreensaver/deepin-custom-screensaver/src/slideshowconfigdialog.h
- src/configs/org.deepin.screensaver.json
- src/dbusscreensaver.cpp
- src/dbusscreensaver.h
- src/src.pro
- src/utils.cpp
- src/utils.h
Log: Add dconfig in screensaver.
Task:
> feat: ScreenSaver add dconfig

- customscreensaver/deepin-custom-screensaver/src/slideshowconfig.cpp
Return default path if path config is invalid.
> fix: Return default path if path config is invalid. 

- debian/changelog
chore: update version 5.0.20
update version 5.0.20
Log: update version 5.0.20
> chore: update version 5.0.20

- src/configs/dbus/ScreenSaverAdaptor.cpp
- src/configs/dbus/ScreenSaverAdaptor.h
- src/configs/json/org_deepin_customscreensaver.hpp
- src/configs/json/org_deepin_screensaver.hpp
- Add ScreenSaverAdaptor for DBus interface
- Add org_deepin_screensaver config class
- Add org_deepin_customscreensaver config class
Log: add screensaver config and dbus adaptor
> chore: add screensaver config and dbus adaptor

- customscreensaver/deepin-custom-screensaver/src/main.cpp
- customscreensaver/deepin-custom-screensaver/src/slideshowscreensaver.cpp
- debian/deepin-screensaver-xscreensaver-data.postinst
- src/main.cpp
- tools/preview/CMakeLists.txt
- Optimize SlideshowScreenSaver::showDefaultBlack() method for better performance
- Update Qt version check in main.cpp for proper compatibility
- Modify CMakeLists.txt to conditionally wrap UI files based on Qt version
Log: [ui] Solve the scaling problem
Bug: https://pms.uniontech.com/bug-view-251573.html
> fix: [ui] Solve the scaling problem
